# Generated by Django 5.2.17 on 2026-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
