# Generated by Django 5.2.17 on 2026-09-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartview_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartView",
            new_name="Cart",
        ),
    ]
