# Generated by Django 5.2.17 on 2026-09-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
